import "./global.css";
import type { Metadata } from "next";
import { Locale, i18n } from "@/src/i18n.config";
import Header from "@/src/components/includes/header";
import Footer from "@/src/components/includes/footer";
import Head from "next/head";

import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  return (
    <html lang={params.lang}>
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body className={`${inter.className}`}>
        <Header lang={params.lang} />
        <main
          className=" p-2 min-h-screen pt-20
          bg-[#d4dfe4] text-[#131313] font-semibold" // dfe4d4 a6b4bf
        >
          {children}
        </main>
        <Footer></Footer>
      </body>
    </html>
  );
}
