import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/src/style/";
import Header from "@/src/app/components/includes/header";
import Footer from "@/src/app/components/includes/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body className={inter.className}>
        <Header></Header>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
